nodeLinker: pnp

packageExtensions:
  "@material/switch@*":
    dependencies:
      "@material/density": "*"
  "@material/touch-target@*":
    dependencies:
      "@material/base": "*"
  vite-multiple-assets@*:
    dependencies:
      mime-types: "*"

plugins:
  - checksum: 50414773926286d8c0fc32e9936a799ad23296281046f03674bc33517b597e1ff7856092c3fcf8d5460a29549ef8b3dca3f59a1732b650a02bf523b255d726e7
    path: .yarn/plugins/@yarnpkg/plugin-ts-project-linker.cjs
    spec: "https://raw.githubusercontent.com/Wroud/foundation/refs/heads/main/packages/yarn-plugin-ts-project-linker/bundles/%40yarnpkg/plugin-ts-project-linker.js"
